*
* [ Telescope positions, for CORSIKA IACT option ] 
*
* Positions refer to OBSLEV 2147.E2
*
*
* 14 MSTs:
*
#ifndef NO_MSTS
* (Alpha,Beta)
TELESCOPE      0.00E2       0.00E2      24.00E2       9.15E2  # (ID=5)   MSTS   01   A0A
TELESCOPE      1.45E2     151.07E2      25.00E2       9.15E2  # (ID=6)   MSTS   02   A4A
TELESCOPE     -1.45E2    -151.07E2      31.00E2       9.15E2  # (ID=7)   MSTS   03   A3A
TELESCOPE    150.79E2      73.60E2      21.00E2       9.15E2  # (ID=8)   MSTS   04   C2A
TELESCOPE    149.35E2     -76.48E2      26.00E2       9.15E2  # (ID=9)   MSTS   05   C1A
TELESCOPE    152.38E2     238.67E2      24.00E2       9.15E2  # (ID=10)   MSTS   06   C4A
TELESCOPE    147.77E2    -241.55E2      30.00E2       9.15E2  # (ID=11)   MSTS   07   C3A
TELESCOPE    313.15E2      -3.00E2      19.00E2       9.15E2  # (ID=12)   MSTS   08   F0A
TELESCOPE   -150.79E2     -73.59E2      28.00E2       9.15E2  # (ID=13)   MSTS   09   X1A
TELESCOPE   -149.35E2      76.48E2      28.00E2       9.15E2  # (ID=14)   MSTS   10   X2A
TELESCOPE   -152.38E2    -238.67E2      38.50E2       9.15E2  # (ID=15)   MSTS   11   X3A
TELESCOPE   -147.77E2     241.55E2      27.00E2       9.15E2  # (ID=16)   MSTS   12   X4A
TELESCOPE   -314.70E2    -159.07E2      35.00E2       9.15E2  # (ID=17)   MSTS   13   V1A
TELESCOPE   -311.59E2     165.08E2      30.50E2       9.15E2  # (ID=18)   MSTS   14   V2A
#endif
*
*
* No SCTs included with Alpha Layout.
*
